services:
  netbird-client:
    hostname: ${NB_HOSTNAME}
    env_file:
      - ${NB_SECRET_ENV_FILE}
    environment:
      - "NB_MANAGEMENT_URL=${NB_MANAGEMENT_URL}"
    volumes:
      - ${NB_DATA:-netbird-client}:/var/lib/netbird
    image: netbirdio/netbird:${NB_TAG:-latest}
    restart: unless-stopped
