---
# (Minimum viable service - based on source-of-truth.yml)
services:
  netbird-client:
    image: ${IMAGE:-netbirdio/netbird}:${TAG:-latest}
    environment:
      - "NB_MANAGEMENT_URL=${NB_MANAGEMENT_URL}"
    volumes:
      - ${DATA:-data}:/var/lib/netbird
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  data:
