---

# (Converted from server-generated install script using it-tools.tech)

# Source:

# docker run --rm -d \
#   --cap-add=NET_ADMIN \
#   -e NB_SETUP_KEY=<NB_SETUP_KEY> \
#   -v netbird-client:/var/lib/netbird \
#   -e NB_MANAGEMENT_URL=<NB_MANAGEMENT_URL> \
#   netbirdio/netbird:latest

services:
    netbird:
        image: 'netbirdio/netbird:latest'
        environment:
            - NB_MANAGEMENT_URL=<NB_MANAGEMENT_URL>
            - NB_SETUP_KEY=<NB_SETUP_KEY>
        volumes:
            - 'netbird-client:/var/lib/netbird'
        cap_add:
            - NET_ADMIN
